### ISSUE TITLE
How start app?

### ISSUE THREAD

**Issue by VicMahoney** [GhostPoro/InterUpTool#1]
Hello!How to use?

**Comment by GhostPoro** [comment]
Hello! Here https://github.com/GhostPoro/InterUpTool/tree/main/builds lives already complied versions of this app. You can run it as Java runnable with double click, or from console as java executable with
`java -jar /path_to_jar/interuptool_v0.04.jar`

be aware, to utilize this tool you need to download at least ffmpeg and Real-ESRGAN.
Tool will show warning, if not find proper realesrgan-ncnn-vulkan-linux/windows/mac executable, with option to open settings script with extremely detailed commentary.

Here you can download upscaler and model
https://github.com/xinntao/Real-ESRGAN/releases/tag/v0.2.5.0

ffmpeg:
https://ffmpeg.org/download.html

Its just automation tool to help users upscale images/video with external applications, with focus on users freedom to modify automation process. So you need make several steps before using it. If you want one-click-magic-box, You can consider using something like https://nmkd.itch.io/flowframes. :)

**Comment by VicMahoney** [comment]
> Hello! Here https://github.com/GhostPoro/InterUpTool/tree/main/builds lives already complied versions of this app. You can run it as Java runnable with double click, or from console as java executable with `java -jar /path_to_jar/interuptool_v0.04.jar`
> 
> be aware, to utilize this tool you need to download at least ffmpeg and Real-ESRGAN. Tool will show warning, if not find proper realesrgan-ncnn-vulkan-linux/windows/mac executable, with option to open settings script with extremely detailed commentary.
> 
> Here you can download upscaler and model https://github.com/xinntao/Real-ESRGAN/releases/tag/v0.2.5.0
> 
> ffmpeg: https://ffmpeg.org/download.html
> 
> Its just automation tool to help users upscale images/video with external applications, with focus on users freedom to modify automation process. So you need make several steps before using it. If you want one-click-magic-box, You can consider using something like https://nmkd.itch.io/flowframes. :)

Do you speak rus?

**Comment by GhostPoro** [comment]
> Do you speak rus?

да

**Comment by VicMahoney** [comment]
> > Do you speak rus?
> 
> да

Тогда приветствую! А кроме Real-ESRGAN, какие-то модели можно использовать типо srmd?
И вопрос про интерполяцию, последние модели на гитхабе - там чуть-ли не до версии 5.0 дошли. В ваш интерфейс можно добавить?

**Comment by VicMahoney** [comment]
И вопрос, Вы сами занимаетесь улучшением видео\фото?
У меня практика по улучшению старых видео в разрешении 320*480 с телефона и видеокамер, достаточно много. Пробовал realesrgan в паре приложений waifu2x и каком-то еще - вроде бы неплохо чистит, но долго (видео 30 минут до 12-16 часов на rtx 3060ti). Другие алгоритмы похуже работают. Вдруг что подскажете для обработки.

**Comment by GhostPoro** [comment]
Для данного инструмента, нет разницы с какой моделью работать. По идее он проверяет только исполняемый файл Real-ESRGAN и FFMPEG.
Какую модель ему укажите в переменных - с той и будет работать (опция  -n)
```
$UPSCALER_AI_APP_PATH$ = ./realesrgan-ncnn-vulkan-20220424/realesrgan-ncnn-vulkan-linux
$VIDEO_PROCESSING_STAGE_FRAMES_UPSCALING_OUT$ = $UPSCALER_AI_APP_PATH$ -i $CURRENT_STAGE_INPUT_FRAMES_FILES_LOCATION_PATH$ -o $CURRENT_STAGE_OUTPUT_FRAMES_FILES_LOCATION_PATH$ -n realesr-animevideov3 -s 2 -f $FRAMES_EXTENSION$
```

По поводу ускорения - сам апскейлинг, по моему мнению, ускорить нет возможности.
Можно ускорить видео енкодинг поиграв с опциями, перенеся его на GPU.
В скрипте есть даже параграф под эти опции:
```
# Video encode Library:
# Common used libs:
#      h264_amf   - H.264 AMD GPU Encoding
#      h264_nvenc - H.264 NVIDIA GPU Encoding
#      libx264    - H.264 CPU Encoding
#
#      hevc_amf   - H.265 AMD GPU Encoding
#      hevc_nvenc - H.265 NVIDIA GPU Encoding
#      libx265    - H.265 CPU Encoding
# Get full list: ffmpeg -encoders
# Note:	In my personal experience, on NVIDIA RTX 2070,
# 		using h264_nvenc just crushes ffmpeg,
#		so using GPU specific lib, can be less reliable.
#$VIDEO_ENCODE_LIB$ = -c:v libx265 -vtag hvc1 -pix_fmt yuv420p -preset veryslow
#$VIDEO_ENCODE_LIB$ = -c:v hevc_nvenc -vtag hvc1 -pix_fmt yuv420p -preset slow
$VIDEO_ENCODE_LIB$ = -c:v libx265 -vtag hvc1 -pix_fmt yuv420p -preset veryslow
```

**Comment by VicMahoney** [comment]
@GhostPoro  Понял, спасибо за ответ!
